name: Deploy to github pages
on:
  push:
    branches:
      - master
jobs:
  gh-pages-deploy:
    name: 🚀 Deploying to Github pages
    runs-on: ubuntu-latest
    steps:
      - name: 🔧 Setup Node.js for use with actions
        uses: actions/setup-node@v1.1.0
        with:
          node-version: "10.x"
          check-latest: false

      - name: 🔀 Checkout the repository
        uses: actions/checkout@v2

      - name: 📦 Clean dependencies
        run: npm ci

      - name: 🚀 Run deploy script
        run: |
          git config user.name ${{ secrets.GH_NAME }} && git config user.email ${{ secrets.GH_EMAIL }}
          npm run github-deploy
